import { LLMTopic } from "../../schema";

/**
 * Output from the clustering LLM call
 * @property taxonomy - Array of topics with their subtopics generated by the model
 */
export type ClusteringModelOutput = {
  taxonomy: Array<LLMTopic>;
};

/**
 * Row of input data for comparing LLM output against
 * @property comments - Raw comments string to be clustered into topics
 */
export type ClusteringDatasetRow = {
  comments: string;
};

/**
 * Input type for all clustering scorers
 * All clustering scorers must use this input format
 * @property modelOutput - The output from the clustering model
 * @property datasetRow - The original dataset row with input comments
 */
export type ClusteringScorerInput = {
  modelOutput: ClusteringModelOutput;
  datasetRow: ClusteringDatasetRow;
};

/**
 * Output for the JSON structure scorer
 * @property valid_json_structure - Whether the output matches the expected JSON schema
 * @property topic_count - Number of topics generated
 * @property total_subtopics - Total number of subtopics across all topics
 * @property reason - Reason valid_json_structure was flagged false
 * @property error - System error message
 */
export type JsonStructureScorerOutput = {
  valid_json_structure: boolean;
  topic_count?: number;
  total_subtopics?: number;
  reason?: string;
  error?: string;
};

/**
 * Output for the topic coverage scorer
 * @property topic_coverage_score - Overall score from 0-1 for topic coverage quality
 * @property topic_count - Number of topics generated
 * @property avg_subtopics_per_topic - Average number of subtopics per topic
 * @property topic_count_score - Score from 0-1 for appropriateness of topic count
 * @property subtopic_diversity_score - Score from 0-1 for subtopic distribution quality
 * @property reason - Reason for having a 0 score
 */
export type TopicCoverageScorerOutput = {
  topic_coverage_score?: number;
  topic_count?: number;
  avg_subtopics_per_topic?: number;
  topic_count_score?: number;
  subtopic_diversity_score?: number;
  reason?: string;
};

/**
 * Output of the LLM judge scorer
 * @property llm_judge_score - Overall score from 0-1 as judged by the LLM
 * @property topic_coverage_score - Score for how well topics cover the input comments
 * @property subtopic_coverage_score - Score for how well subtopics align within topics
 * @property reasoning - Brief explanation of the scores
 * @property error - Error message if evaluation failed
 */
export type LLMJudgeOutput = {
  llm_judge_score: number;
  topic_coverage_score?: number;
  subtopic_coverage_score?: number;
  reasoning?: string;
  error?: unknown;
};

/**
 * Function signature for LLM judge scorer
 */
export type LLMJudgeScorerFunction = (
  args: ClusteringScorerInput,
) => Promise<LLMJudgeOutput>;
