/**
 * Example usage of the claims extraction pipeline step
 *
 * This demonstrates how to use the extractClaims function to extract
 * structured claims from comments and organize them by topic/subtopic.
 *
 * To run this example:
 * 1. Set OPENAI_API_KEY environment variable
 * 2. Run: npx ts-node src/pipeline-steps/claims/example.ts
 */

import { extractClaims } from "./index";
import type { ClaimsTree, Comment, LLMConfig, Topic } from "./types";

/**
 * Example comments about pets
 */
function getExampleComments(): Comment[] {
  return [
    {
      id: "c1",
      text: "I love cats. They are independent and clean animals that don't require constant attention.",
      speaker: "Alice",
    },
    {
      id: "c2",
      text: "Dogs are great companions. They are loyal and friendly, always happy to see you.",
      speaker: "Bob",
    },
    {
      id: "c3",
      text: "I'm not sure about birds as pets. They can be noisy and require special care.",
      speaker: "Charlie",
    },
    {
      id: "c4",
      text: "Cats are low maintenance compared to dogs. You don't need to walk them every day.",
      speaker: "Diana",
    },
    {
      id: "c5",
      text: "Dogs need regular exercise and walks, which is good for the owner too.",
      speaker: "Eve",
    },
    {
      id: "c6",
      text: "Birds can be beautiful and entertaining, but they need a proper cage setup.",
      speaker: "Frank",
    },
  ];
}

/**
 * Example taxonomy (typically generated by clustering step)
 */
function getExampleTaxonomy(): Topic[] {
  return [
    {
      topicName: "Pet Characteristics",
      topicShortDescription:
        "General characteristics and traits of different pets",
      subtopics: [
        {
          subtopicName: "Independence",
          subtopicShortDescription: "How independent pets are",
        },
        {
          subtopicName: "Social Behavior",
          subtopicShortDescription: "Social and interactive behaviors",
        },
        {
          subtopicName: "Maintenance",
          subtopicShortDescription: "Care and maintenance requirements",
        },
      ],
    },
    {
      topicName: "Pet Care Requirements",
      topicShortDescription: "What different pets need in terms of care",
      subtopics: [
        {
          subtopicName: "Exercise",
          subtopicShortDescription: "Exercise and activity needs",
        },
        {
          subtopicName: "Housing",
          subtopicShortDescription: "Housing and living space requirements",
        },
        {
          subtopicName: "Attention",
          subtopicShortDescription: "Amount of attention required",
        },
      ],
    },
  ];
}

/**
 * LLM configuration for claims extraction
 */
function getLLMConfig(): LLMConfig {
  return {
    model_name: "gpt-4o-mini",
    system_prompt: `You are a professional research assistant extracting claims from user comments.
Extract specific, factual claims made by each speaker. Each claim should be:
- A clear, standalone statement
- Supported by a direct quote from the comment
- Classified into the appropriate topic and subtopic from the provided taxonomy`,
    user_prompt: `Extract all claims from the following comment.
For each claim, provide:
- claim: A concise statement of what is being claimed
- quote: The exact text from the comment that supports this claim
- topicName: The topic this claim belongs to (must match taxonomy)
- subtopicName: The subtopic this claim belongs to (must match taxonomy)

Return a JSON object of the form {
  "claims": [
    {
      "claim": "Clear statement of the claim",
      "quote": "Exact supporting quote",
      "topicName": "Topic Name",
      "subtopicName": "Subtopic Name"
    }
  ]
}`,
  };
}

/**
 * Count total claims across all topics
 */
function countTotalClaims(claimsTree: ClaimsTree): number {
  let total = 0;
  for (const topicName in claimsTree) {
    total += claimsTree[topicName].total;
  }
  return total;
}

/**
 * Display a single claim
 */
function displayClaim(claim: {
  claim: string;
  quote: string;
  speaker: string;
}): void {
  console.log(`    - "${claim.claim}" (${claim.speaker})`);
  console.log(`      Quote: "${claim.quote}"`);
}

/**
 * Display claims for a subtopic
 */
function displaySubtopic(
  subtopicName: string,
  subtopic: {
    total: number;
    claims: Array<{ claim: string; quote: string; speaker: string }>;
  },
): void {
  if (subtopic.total === 0) return;

  console.log(`  ${subtopicName} (${subtopic.total} claims):`);
  for (const claim of subtopic.claims) {
    displayClaim(claim);
  }
}

/**
 * Display claims for a topic
 */
function displayTopic(
  topicName: string,
  topic: {
    total: number;
    subtopics: Record<
      string,
      {
        total: number;
        claims: Array<{ claim: string; quote: string; speaker: string }>;
      }
    >;
  },
): void {
  console.log(`\n${topicName} (${topic.total} claims):`);

  for (const subtopicName in topic.subtopics) {
    displaySubtopic(subtopicName, topic.subtopics[subtopicName]);
  }
}

/**
 * Display usage statistics
 */
function displayUsageStats(
  usage: { input_tokens: number; output_tokens: number; total_tokens: number },
  cost: number,
): void {
  console.log("\n=== USAGE STATS ===");
  console.log("Prompt tokens:", usage.input_tokens);
  console.log("Completion tokens:", usage.output_tokens);
  console.log("Total tokens:", usage.total_tokens);
  console.log(`Estimated cost: $${cost.toFixed(4)}`);
}

/**
 * Display claims organized by topic and subtopic
 */
function displayResults(
  claimsTree: ClaimsTree,
  usage: { input_tokens: number; output_tokens: number; total_tokens: number },
  cost: number,
): void {
  console.log("\n=== RESULTS ===\n");

  const totalClaims = countTotalClaims(claimsTree);
  console.log("Total claims extracted:", totalClaims);
  console.log("\nClaims by Topic:");

  for (const topicName in claimsTree) {
    displayTopic(topicName, claimsTree[topicName]);
  }

  displayUsageStats(usage, cost);
}

async function main() {
  // Check for API key
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    console.error("Error: OPENAI_API_KEY environment variable not set");
    process.exit(1);
  }

  const comments = getExampleComments();
  const taxonomy = getExampleTaxonomy();
  const llmConfig = getLLMConfig();

  console.log("Extracting claims from comments...\n");

  // Call the claims extraction function
  const result = await extractClaims(comments, taxonomy, llmConfig, apiKey, {
    reportId: "example-report",
    userId: "example-user",
  });

  if (result.tag === "failure") {
    console.error("Error:", result.error);
    process.exit(1);
  }

  const { data: claimsTree, usage, cost } = result.value;
  displayResults(claimsTree, usage, cost);
}

main().catch((error) => {
  console.error("Error:", error);
  process.exit(1);
});
