/**
 * Shared type definitions for pipeline steps
 */

import type OpenAI from "openai";

/**
 * Base class for all clustering errors
 */
export class ClusteringError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "ClusteringError";
  }
}

/**
 * Error thrown when the API call fails
 */
export class ApiCallFailedError extends ClusteringError {
  constructor(
    public modelName: string,
    public reason: string,
  ) {
    super(`API call failed for model ${modelName}: ${reason}`);
    this.name = "ApiCallFailedError";
  }
}

/**
 * Error thrown when the API returns no content
 */
export class EmptyResponseError extends ClusteringError {
  constructor(public modelName: string) {
    super(`No response from clustering model: ${modelName}`);
    this.name = "EmptyResponseError";
  }
}

/**
 * Error thrown when JSON parsing fails
 */
export class ParseFailedError extends ClusteringError {
  constructor(
    public content: string,
    public reason: string,
  ) {
    super(`Failed to parse clustering response: ${reason}`);
    this.name = "ParseFailedError";
  }
}

/**
 * A single comment from a user
 * @property id - Unique identifier for the comment
 * @property text - The comment text content
 * @property speaker - Name or identifier of the person who made the comment
 * @property interview - Optional interview identifier or context
 */
export interface Comment {
  id: string;
  text: string;
  speaker: string;
  interview?: string;
}

/**
 * Configuration for LLM API calls
 * @property model_name - Name of the OpenAI model to use (e.g., "gpt-4o-mini")
 * @property system_prompt - System-level instructions for the LLM
 * @property user_prompt - User-level prompt template
 */
export interface LLMConfig {
  model_name: string;
  system_prompt: string;
  user_prompt: string;
}

/**
 * A subtopic within a larger topic
 * @property subtopicName - Concise name of the subtopic
 * @property subtopicShortDescription - Brief description of the subtopic (70-90 words)
 */
export interface Subtopic {
  subtopicName: string;
  subtopicShortDescription: string;
}

/**
 * A topic containing related subtopics
 * @property topicName - Concise name of the topic
 * @property topicShortDescription - Brief description of the topic (25-35 words)
 * @property subtopics - Array of related subtopics
 */
export interface Topic {
  topicName: string;
  topicShortDescription: string;
  subtopics: Subtopic[];
}

/**
 * A taxonomy structure containing topics
 * @property taxonomy - Array of topics
 */
export interface Taxonomy {
  taxonomy: Topic[];
}

/**
 * Token usage statistics from an LLM API call
 * @property prompt_tokens - Number of tokens in the input prompt
 * @property completion_tokens - Number of tokens in the model's response
 * @property total_tokens - Total tokens used (prompt + completion)
 */
export interface TokenUsage {
  input_tokens: number;
  output_tokens: number;
  total_tokens: number;
}

/**
 * Result from topic tree generation
 * @property data - Array of generated topics with subtopics
 * @property usage - Token usage statistics
 * @property cost - Estimated cost in USD
 */
export interface TopicTreeResult {
  data: Topic[];
  usage: TokenUsage;
  cost: number;
}

/**
 * Options for clustering operations
 * @property reportId - Optional identifier for the report being processed
 * @property userId - Optional identifier for the user making the request
 * @property enableWandB - Optional flag to enable Weights & Biases logging
 */
export interface ClusteringOptions {
  reportId?: string;
  userId?: string;
  enableWandB?: boolean;
}

/**
 * Input for clustering model evaluation
 * @property comments - Raw comments text to be clustered
 */
export interface ClusteringInput {
  comments: string;
}

/**
 * Output from clustering model with usage tracking
 * @property taxonomy - Array of topics generated by the clustering model
 * @property usage - Token usage statistics from the API call
 * @property cost - Estimated cost in USD for the API call
 */
export interface ClusteringOutput {
  taxonomy: Topic[];
  usage: TokenUsage;
  cost: number;
}

/**
 * A single claim extracted from a comment
 * @property claim - The concise extracted claim text
 * @property quote - The exact quote from the comment supporting this claim
 * @property speaker - The speaker who made the comment
 * @property topicName - The topic this claim belongs to
 * @property subtopicName - The subtopic this claim belongs to
 * @property commentId - The ID of the source comment
 */
export interface Claim {
  claim: string;
  quote: string;
  speaker: string;
  topicName: string;
  subtopicName: string;
  commentId: string;
}

/**
 * Claims grouped under a subtopic
 * @property total - Total number of claims in this subtopic
 * @property claims - Array of claims in this subtopic
 */
export interface SubtopicClaimNode {
  total: number;
  claims: Claim[];
}

/**
 * Subtopics with their claims, grouped under a topic
 * @property total - Total number of claims in this topic across all subtopics
 * @property subtopics - Record mapping subtopic names to their claim nodes
 */
export interface TopicClaimNode {
  total: number;
  subtopics: Record<string, SubtopicClaimNode>;
}

/**
 * The complete claims tree structure
 * Maps topic names to their claim nodes
 */
export type ClaimsTree = Record<string, TopicClaimNode>;

/**
 * Result from claims extraction
 * @property data - The claims tree with all extracted claims organized by topic/subtopic
 * @property usage - Token usage statistics from the LLM calls
 * @property cost - Estimated total cost in USD
 */
export interface ClaimsResult {
  data: ClaimsTree;
  usage: TokenUsage;
  cost: number;
}

/**
 * Options for claims extraction
 * @property reportId - Optional identifier for the report being processed
 * @property userId - Optional identifier for the user making the request
 * @property enableScoring - Optional flag to enable evaluation scoring
 */
export interface ClaimsOptions {
  reportId?: string;
  userId?: string;
  enableScoring?: boolean;
}

/**
 * Output from claims extraction model
 * @property claims - Array of claims with topic/subtopic assignments (without speaker/commentId)
 */
export interface ClaimsOutput {
  claims: Array<{
    claim: string;
    quote: string;
    topicName: string;
    subtopicName: string;
  }>;
}

/**
 * Full result from claims extraction model including usage and cost
 * @property claims - Array of extracted claims with all metadata
 * @property usage - Token usage statistics from the API call
 * @property cost - Estimated cost in USD for the API call
 */
export interface ClaimsModelResult {
  claims: Claim[];
  usage: TokenUsage;
  cost: number;
}

/**
 * Input parameters for claims extraction from a single comment
 */
export interface ExtractClaimsInput {
  /** OpenAI client instance */
  openaiClient: OpenAI;
  /** Model name (e.g., "gpt-4o-mini") */
  modelName: string;
  /** System prompt */
  systemPrompt: string;
  /** User prompt template */
  userPrompt: string;
  /** The comment text to extract claims from */
  commentText: string;
  /** Array of topics with subtopics */
  taxonomy: Topic[];
  /** The speaker who made the comment */
  speaker: string;
  /** The ID of the comment */
  commentId: string;
  /** Optional evaluation options */
  options?: {
    enableScoring?: boolean;
    weaveProjectName?: string;
  };
}
