/**
 * Shared type definitions for pipeline steps
 */

/**
 * Base class for all clustering errors
 */
export class ClusteringError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "ClusteringError";
  }
}

/**
 * Error thrown when the API call fails
 */
export class ApiCallFailedError extends ClusteringError {
  constructor(
    public modelName: string,
    public reason: string,
  ) {
    super(`API call failed for model ${modelName}: ${reason}`);
    this.name = "ApiCallFailedError";
  }
}

/**
 * Error thrown when the API returns no content
 */
export class EmptyResponseError extends ClusteringError {
  constructor(public modelName: string) {
    super(`No response from clustering model: ${modelName}`);
    this.name = "EmptyResponseError";
  }
}

/**
 * Error thrown when JSON parsing fails
 */
export class ParseFailedError extends ClusteringError {
  constructor(
    public content: string,
    public reason: string,
  ) {
    super(`Failed to parse clustering response: ${reason}`);
    this.name = "ParseFailedError";
  }
}

/**
 * A single comment from a user
 * @property id - Unique identifier for the comment
 * @property text - The comment text content
 * @property speaker - Name or identifier of the person who made the comment
 * @property interview - Optional interview identifier or context
 */
export interface Comment {
  id: string;
  text: string;
  speaker: string;
  interview?: string;
}

/**
 * Configuration for LLM API calls
 * @property model_name - Name of the OpenAI model to use (e.g., "gpt-4o-mini")
 * @property system_prompt - System-level instructions for the LLM
 * @property user_prompt - User-level prompt template
 */
export interface LLMConfig {
  model_name: string;
  system_prompt: string;
  user_prompt: string;
}

/**
 * A subtopic within a larger topic
 * @property subtopicName - Concise name of the subtopic
 * @property subtopicShortDescription - Brief description of the subtopic (70-90 words)
 */
export interface Subtopic {
  subtopicName: string;
  subtopicShortDescription: string;
}

/**
 * A topic containing related subtopics
 * @property topicName - Concise name of the topic
 * @property topicShortDescription - Brief description of the topic (25-35 words)
 * @property subtopics - Array of related subtopics
 */
export interface Topic {
  topicName: string;
  topicShortDescription: string;
  subtopics: Subtopic[];
}

/**
 * A taxonomy structure containing topics
 * @property taxonomy - Array of topics
 */
export interface Taxonomy {
  taxonomy: Topic[];
}

/**
 * Token usage statistics from an LLM API call
 * @property prompt_tokens - Number of tokens in the input prompt
 * @property completion_tokens - Number of tokens in the model's response
 * @property total_tokens - Total tokens used (prompt + completion)
 */
export interface TokenUsage {
  input_tokens: number;
  output_tokens: number;
  total_tokens: number;
}

/**
 * Result from topic tree generation
 * @property data - Array of generated topics with subtopics
 * @property usage - Token usage statistics
 * @property cost - Estimated cost in USD
 */
export interface TopicTreeResult {
  data: Topic[];
  usage: TokenUsage;
  cost: number;
}

/**
 * Options for clustering operations
 * @property reportId - Optional identifier for the report being processed
 * @property userId - Optional identifier for the user making the request
 * @property enableWandB - Optional flag to enable Weights & Biases logging
 */
export interface ClusteringOptions {
  reportId?: string;
  userId?: string;
  enableWandB?: boolean;
}

/**
 * Input for clustering model evaluation
 * @property comments - Raw comments text to be clustered
 */
export interface ClusteringInput {
  comments: string;
}

/**
 * Output from clustering model with usage tracking
 * @property taxonomy - Array of topics generated by the clustering model
 * @property usage - Token usage statistics from the API call
 * @property cost - Estimated cost in USD for the API call
 */
export interface ClusteringOutput {
  taxonomy: Topic[];
  usage: TokenUsage;
  cost: number;
}
