name: Deploy Pyserver to Cloud Run - Production

on:
  workflow_dispatch:

jobs:
  pre-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: log execution mode
        run: |
          if [ "${{ github.event.act }}" = "true" ]; then
              echo "::notice:: Running locally with act - pyserver prod deploy skipped"
            else
              echo "::notice:: Running in CI - deploying pyserver prod"
            fi
  deploy:
    name: Deploy Pyserver - Production
    if: ${{!github.event.act}}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY2 }}"

      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: tttc-light-js
      ####
      - name: Write .env file for Pyserver
        run: |
          echo "${{ secrets.ENV_PYSERVER }}" > pyserver/.env

      - name: Build Docker image
        run: |
          docker build -t gcr.io/tttc-light-js/pyserver-brandon -f pyserver/Dockerfile .

      - name: Push Docker image
        run: |
          gcloud auth configure-docker
          docker push gcr.io/tttc-light-js/pyserver-brandon

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy pyserver-brandon \
            --image gcr.io/tttc-light-js/pyserver-brandon \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated

      - name: Remove .env file
        run: rm -f pyserver/.env
